<script lang="ts">
  import { page } from '$app/state';
  import { onDestroy, onMount } from 'svelte';
  import { api, base, FriendlyError } from '$lib/api/client';
  import { auth } from '$lib/auth.svelte';
  import { connection } from '$lib/realtime.svelte';
  import { localDate, localDateTime, localTime, parseApiTime, relativeTime } from '$lib/time';
  import { statusLabel, type History, type Location, type Related, type Report } from '$lib/types';
  import ReportMap from '$lib/components/ReportMap.svelte';
  import LiveVideo from '$lib/components/LiveVideo.svelte';
  import SavedVideoPlayer from '$lib/components/SavedVideoPlayer.svelte';
  type StreamInfo = {active:boolean;requested:boolean;recording:boolean;recording_available:boolean;viewer_url?:string;access_token?:string};
  type SavedVideo = {id:string;label:string;mime_type:string;size:number|null;created_at:string};
  type Reporter = {name:string;email:string;phone:string|null;joined_at:string;last_login_at:string|null;total_reports:number;active_reports:number;resolved_reports:number;reports:Report[]};
  let report=$state<Report|null>(null);let reporter=$state<Reporter|null>(null);let location=$state<Location|null>(null);let history=$state<History[]>([]);let related=$state<Related|null>(null);let stream=$state<StreamInfo|null>(null);let videos=$state<SavedVideo[]>([]);let videoUrls=$state<Record<string,string>>({});let error=$state('');let busy=$state('');let now=$state(Date.now());
  const stale=$derived(location ? now-parseApiTime(location.recorded_at).getTime()>120000 : false);
  const directionUrl=$derived(report ? `https://www.google.com/maps/dir/?api=1&destination=${report.initial_latitude},${report.initial_longitude}` : '#');
  const appTranscript=$derived.by(()=>{const item=[...history].reverse().find(entry=>entry.event==='SIGN_TRANSCRIBED');const value=item?.event_metadata.transcript;return typeof value==='string'?value:''});

  const eventLabel:Record<string,string>={REPORT_CREATED:'Report received',OFFICE_ASSIGNED:'Sent to responsible office',OFFICER_ACKNOWLEDGED:'Officer acknowledged the report',OFFICER_ASSIGNED:'Officer assigned',RESPONDING:'Officer responding',ARRIVED:'Officer arrived',RESOLVED:'Report resolved',PRIORITY_CHANGED:'Priority updated',LOCATION_UPDATED:'Location updated',VIDEO_STARTED:'Live video started',VIDEO_STOPPED:'Live video stopped',SIGN_TRANSCRIBED:'Signing video transcribed'};
  async function load(){try{[report,reporter,location,history,related,stream,videos]=await Promise.all([api<Report>(`/officer/reports/${page.params.id}`),api<Reporter>(`/officer/reports/${page.params.id}/reporter`),api<Location|null>(`/officer/reports/${page.params.id}/location`),api<History[]>(`/officer/reports/${page.params.id}/history`),api<Related>(`/officer/reports/${page.params.id}/related`),api<StreamInfo>(`/reports/${page.params.id}/stream`),api<SavedVideo[]>(`/officer/reports/${page.params.id}/videos`)]);localStorage.setItem(`report:${page.params.id}`,JSON.stringify({report,location,history,related}));}catch(e){const cached=localStorage.getItem(`report:${page.params.id}`);if(cached)({report,location,history,related}=JSON.parse(cached));else error=e instanceof Error?e.message:'Report is unavailable.';}}
  async function action(name:string){busy=name;error='';try{report=await api<Report>(`/officer/reports/${page.params.id}/${name}`,{method:'POST'});await load()}catch(e){error=e instanceof FriendlyError?e.message:'This action could not be completed.'}finally{busy=''}}
  async function requestVideo(){busy='video';try{stream=await api<StreamInfo>(`/officer/reports/${page.params.id}/stream/request`,{method:'POST'})}catch(e){error=e instanceof Error?e.message:'The request could not be sent.'}finally{busy=''}}
  async function watchSaved(video:SavedVideo){busy=`saved-${video.id}`;error='';try{const response=await fetch(`${base}/officer/reports/${page.params.id}/videos/${video.id}`,{headers:{Authorization:`Bearer ${auth.accessToken}`}});if(!response.ok)throw new Error('This video could not be opened.');videoUrls={...videoUrls,[video.id]:URL.createObjectURL(await response.blob())}}catch(e){error=e instanceof Error?e.message:'This video could not be opened.'}finally{busy=''}}
  onMount(()=>{load();const timer=setInterval(()=>{now=Date.now();api<StreamInfo>(`/reports/${page.params.id}/stream`).then(value=>stream=value).catch(()=>{});api<SavedVideo[]>(`/officer/reports/${page.params.id}/videos`).then(value=>videos=value).catch(()=>{})},3000);return()=>clearInterval(timer)});
  $effect(()=>{if(connection.lastEvent?.type==='transcription.ready' && connection.lastEvent.report_id===page.params.id)load();});
  onDestroy(()=>Object.values(videoUrls).forEach(url=>URL.revokeObjectURL(url)));
</script>
{#if error && !report}<div class="error">{error}</div>{:else if !report}<div class="skeleton"></div>{:else}
  <div class="page-head"><div><p class="eyebrow {report.priority.toLowerCase()}">{report.priority === 'NORMAL' ? statusLabel[report.status] : `${report.priority} PRIORITY`}</p><h1>{report.category}</h1><p>Reported {relativeTime(report.created_at)} · {report.office.name}</p></div><a class="button" href={directionUrl} target="_blank" rel="noreferrer">Open Directions</a></div>
  {#if error}<div class="error action-error">{error}</div>{/if}
  <div class="detail-grid">
    <section class="panel map-panel"><div class="section-title"><div><h2>{stale ? 'Last known location' : 'Live Location'}</h2><p>{location ? `Updated ${relativeTime(location.recorded_at)}` : 'Location unavailable'}</p></div>{#if stale}<span class="stale">Not updated recently</span>{/if}</div><div class="map-wrap"><ReportMap {report} {location}/></div></section>
    <aside class="side">
      <section class="panel"><h2>Report Details</h2><p class="description">{report.description}</p><dl><div><dt>Status</dt><dd>{statusLabel[report.status]}</dd></div><div><dt>Assigned officer</dt><dd>{report.assigned_officer?.name ?? 'Awaiting acknowledgement'}</dd></div></dl></section>
      <section class="panel"><p class="eyebrow">Sign-language communication</p><h2>Live Video</h2>{#if stream?.active && stream.viewer_url && stream.access_token}<p><span class="live-dot"></span><strong>Live now</strong>{stream.recording ? ' · being saved' : ''}. Watch the user’s signing.</p><LiveVideo url={stream.viewer_url} token={stream.access_token}/>{:else}<p>The user’s camera is not live now. Saved videos remain available below.</p><button class="button secondary" disabled={busy==='video'} onclick={requestVideo}>{busy==='video'?'Sending request…':'Request Live Video'}</button>{/if}</section>
      <section class="panel reporter"><p class="eyebrow">Reporter details</p><h2>{reporter?.name ?? 'Reporter'}</h2>{#if reporter}<dl><div><dt>Email</dt><dd>{reporter.email}</dd></div><div><dt>Phone</dt><dd>{reporter.phone || 'Not provided'}</dd></div><div><dt>Joined</dt><dd>{localDate(reporter.joined_at)}</dd></div><div><dt>Last sign-in</dt><dd>{reporter.last_login_at ? localDateTime(reporter.last_login_at) : 'Not available'}</dd></div></dl><div class="reporter-stats"><div><strong>{reporter.total_reports}</strong><span>Total</span></div><div><strong>{reporter.active_reports}</strong><span>Active</span></div><div><strong>{reporter.resolved_reports}</strong><span>Resolved</span></div></div><h3>Report History</h3><div class="reporter-history">{#each reporter.reports as item (item.public_id)}<a class:current={item.public_id===report.public_id} href={`/reports/${item.public_id}`}><span><strong>{item.category}</strong><small>{localDate(item.created_at)} · {item.office.name}</small></span><em>{statusLabel[item.status]}</em></a>{/each}</div>{/if}</section>
    </aside>
    <section class="panel saved-videos"><h2>Available Videos</h2><p class="video-help">Recorded videos can be paused, replayed, skipped backward or forward, slowed down for clearer signing, viewed fullscreen, or downloaded.</p>{#if videos.length}<div class="video-list">{#each videos as video (video.id)}<article><div><strong>{video.label}</strong><small>{localDateTime(video.created_at)}</small></div>{#if videoUrls[video.id]}<SavedVideoPlayer src={videoUrls[video.id]} label={video.label} downloadName={`${report.public_id}-${video.id}`}/>{:else}<button class="button secondary" disabled={busy===`saved-${video.id}`} onclick={()=>watchSaved(video)}>{busy===`saved-${video.id}`?'Loading…':'Open Video Player'}</button>{/if}</article>{/each}</div>{:else}<p class="muted">No saved videos are available for this report yet.</p>{/if}</section>
    {#if appTranscript}<section id="transcript" class="panel app-transcript"><p class="eyebrow">From the app recording</p><h2>Rough transcript</h2><p>{appTranscript}</p></section>{/if}
    <section class="panel related"><h2>Previous Reports</h2>
<div class="related-grid"><div><h3>Nearby</h3><strong>{related?.nearby.length ?? 0}</strong><span>reports</span></div><div><h3>From this user</h3><strong>{related?.same_user.length ?? 0}</strong><span>reports</span></div><div><h3>Handled by this office</h3><strong>{related?.same_office.length ?? 0}</strong><span>reports</span></div></div>{#if related?.nearby.length}<div class="previous">{#each related.nearby.slice(0,3) as item}<a href={`/reports/${item.public_id}`}><span>{item.category}</span><small>{item.distance_km} km away · {statusLabel[item.status]}</small></a>{/each}</div>{/if}</section>
    <section class="panel timeline"><h2>Timeline</h2>{#if history.length}<ol>{#each history as item}<li><time>{localTime(item.created_at)}</time><span>{eventLabel[item.event]??'Report updated'}</span></li>{/each}</ol>{:else}<p>No timeline entries are available.</p>{/if}</section>
  </div>
  <div class="actions" aria-label="Report actions">{#if report.status==='NEW'}<button class="button" disabled={!!busy} onclick={()=>action('acknowledge')}>{busy?'Working…':'Acknowledge'}</button>{:else if ['ACKNOWLEDGED','ASSIGNED'].includes(report.status)}<button class="button" disabled={!!busy} onclick={()=>action('respond')}>Responding</button>{:else if report.status==='RESPONDING'}<button class="button" disabled={!!busy} onclick={()=>action('arrive')}>Arrived</button>{:else if report.status==='ARRIVED'}<button class="button success" disabled={!!busy} onclick={()=>action('resolve')}>Resolve</button>{:else if report.status==='RESOLVED'}<span>Resolved</span>{/if}<a class="button secondary mobile-direction" href={directionUrl} target="_blank" rel="noreferrer">Open Directions</a></div>
{/if}
<style>
  .reporter-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:.4rem;margin:1rem 0}.reporter-stats div{background:#f3f6f7;border-radius:7px;padding:.6rem;text-align:center}.reporter-stats strong,.reporter-stats span{display:block}.reporter-stats span{font-size:.7rem;color:var(--muted)}.reporter h3{font-size:.9rem;margin:1rem 0 .4rem}.reporter-history{display:grid;max-height:280px;overflow:auto}.reporter-history a{display:flex;justify-content:space-between;gap:.5rem;padding:.65rem 0;border-top:1px solid var(--line);text-decoration:none}.reporter-history a.current{color:var(--blue)}.reporter-history span,.reporter-history small{display:block}.reporter-history small{color:var(--muted);font-size:.7rem}.reporter-history em{font-style:normal;font-size:.7rem;font-weight:700}
  .app-transcript{grid-column:1/-1;border-left:4px solid var(--blue)}.app-transcript p:last-child{font-size:1.25rem;line-height:1.5;color:#193744}.video-help{color:var(--muted);font-size:.8rem;margin:-.3rem 0 1rem}.video-list{display:grid;gap:.8rem}.video-list article{border:1px solid var(--line);border-radius:8px;padding:.8rem;display:grid;gap:.7rem}.video-list article>div{display:flex;justify-content:space-between;gap:1rem}.video-list small,.muted{color:var(--muted)}.saved-videos{grid-column:1/-1}
  .live-dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--red);margin-right:.4rem;box-shadow:0 0 0 4px #c63f3722}.eyebrow.high{color:#8a5100}.eyebrow.critical{color:var(--red)}.detail-grid{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,.7fr);gap:1rem;align-items:start}.panel h2{font-size:1.05rem;margin:0 0 .8rem}.map-panel{padding:0;overflow:hidden}.section-title{display:flex;justify-content:space-between;align-items:center;padding:1rem}.section-title h2,.section-title p{margin:0}.section-title p{font-size:.85rem;color:var(--muted);margin-top:.25rem}.stale{font-size:.75rem;background:#f4e8d5;color:#724700;padding:.3rem .5rem;border-radius:4px}.map-wrap{height:400px}.side{display:grid;gap:1rem}.description{line-height:1.55;color:#34454c}dl{margin:1rem 0 0}dl div{border-top:1px solid var(--line);padding:.7rem 0}dt{font-size:.75rem;color:var(--muted);font-weight:700}dd{margin:.2rem 0 0;font-weight:650}.related,.timeline{grid-column:1/-1}.related-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem}.related-grid div{background:#f3f6f7;border-radius:7px;padding:.8rem}.related-grid h3{font-size:.78rem;margin:0;color:var(--muted)}.related-grid strong{font-size:1.6rem;display:block}.related-grid span{font-size:.78rem;color:var(--muted)}.previous{display:grid;margin-top:.7rem}.previous a{display:flex;justify-content:space-between;padding:.7rem 0;border-top:1px solid var(--line);text-decoration:none}.previous small{color:var(--muted)}ol{list-style:none;margin:0;padding:0}li{display:grid;grid-template-columns:90px 1fr;position:relative;padding:.65rem 0 .65rem 1rem;border-left:2px solid #c8d9dd}li:before{content:'';position:absolute;width:9px;height:9px;border-radius:50%;background:var(--blue);left:-5.5px;top:1rem}time{font-size:.78rem;color:var(--muted)}.actions{position:sticky;bottom:0;background:#f4f6f7ed;backdrop-filter:blur(6px);border-top:1px solid var(--line);padding:1rem 0;display:flex;gap:.7rem;margin-top:1rem}.mobile-direction{display:none}@media(max-width:850px){.detail-grid{grid-template-columns:1fr}.related,.timeline{grid-column:1}.map-wrap{height:330px}}@media(max-width:600px){.page-head .button{display:none}.related-grid{grid-template-columns:1fr 1fr}.related-grid div:last-child{grid-column:1/-1}.actions{position:fixed;z-index:90;bottom:54px;left:0;right:0;padding:.65rem .9rem;background:white}.actions .button{flex:1}.mobile-direction{display:inline-flex}.previous a{display:grid;gap:.25rem}}
</style>
