<script lang="ts">
  import { onMount } from 'svelte';
  import { api, FriendlyError } from '$lib/api/client';
  import { connection } from '$lib/realtime.svelte';
  import { auth } from '$lib/auth.svelte';
  import ReportCard from '$lib/components/ReportCard.svelte';
  import type { ReportsPage, ReportStatus, Priority } from '$lib/types';
  let result=$state<ReportsPage>({items:[],page:1,page_size:100,total:0}); let loading=$state(true); let error=$state(''); let notice=$state(''); let taking=$state(''); let search=$state(''); let status=$state<ReportStatus|''>(''); let priority=$state<Priority|''>(''); let scope=$state<'office'|'all'>('office');
  const availableCount=$derived(result.items.filter(report=>report.status==='NEW'&&!report.assigned_officer).length);
  async function load(page=1){loading=true;error='';const params=new URLSearchParams({page:String(page),page_size:'100',scope});if(search)params.set('search',search);if(status)params.set('status',status);if(priority)params.set('priority',priority);try{result=await api(`/officer/reports?${params}`)}catch(e){error=e instanceof Error?e.message:'Reports are unavailable.'}finally{loading=false}}
  async function setScope(value:'office'|'all'){if(scope===value)return;scope=value;await load(1)}
  async function takeReport(report: import('$lib/types').Report){taking=report.public_id;error='';notice='';try{const updated=await api<import('$lib/types').Report>(`/officer/reports/${report.public_id}/acknowledge`,{method:'POST'});result={...result,items:result.items.map(item=>item.public_id===updated.public_id?updated:item)};notice=`You have taken the ${updated.category} report.`}catch(e){error=e instanceof FriendlyError?e.message:'This report could not be taken.';await load(result.page)}finally{taking=''}}
  onMount(()=>load());
  $effect(()=>{ if(connection.lastEvent?.type && connection.lastEvent.type!=='connected') load(result.page); });
</script>
<div class="page-head"><div><p class="eyebrow">Officer report queue</p><h1>Choose a Report</h1><p>{availableCount} available · {result.total} reports shown</p></div></div>
<div class="scope-row"><div><strong>Report source</strong><span>{scope==='all'?'Every report stored in the database':'Only reports routed to your offices'}</span></div><div class="scope-toggle" role="group" aria-label="Report source"><button class:active={scope==='office'} onclick={()=>setScope('office')}>My Offices</button><button class:active={scope==='all'} onclick={()=>setScope('all')}>All Database Reports</button></div></div>
<div class="queue-guide"><span class="available-dot"></span><strong>Available</strong><span>Select “Take Report” to become the responding officer.</span><span class="taken-dot"></span><strong>Already taken</strong><span>The assigned officer is shown on the report.</span></div>
<form class="filters" onsubmit={(e)=>{e.preventDefault();load()}}><label>Search<input bind:value={search} placeholder="Category or report details" /></label><label>Status<select bind:value={status}><option value="">All statuses</option><option value="NEW">Available Reports</option><option value="ACKNOWLEDGED">Acknowledged</option><option value="RESPONDING">Responding</option><option value="ARRIVED">Arrived</option><option value="RESOLVED">Resolved</option></select></label><label>Priority<select bind:value={priority}><option value="">All priorities</option><option value="CRITICAL">Critical</option><option value="HIGH">High</option><option value="NORMAL">Normal</option></select></label><button class="button">Search</button></form>
{#if notice}<div class="notice" role="status">{notice}</div>{/if}{#if error}<div class="error" role="alert">{error}</div>{/if}
{#if loading}<div class="list"><div class="skeleton"></div><div class="skeleton"></div></div>{:else if result.items.length}<div class="list">{#each result.items as report (report.public_id)}<ReportCard {report} onPick={takeReport} busy={taking===report.public_id}/>{/each}</div><div class="pagination"><button class="button secondary" disabled={result.page===1} onclick={()=>load(result.page-1)}>Previous</button><span>Page {result.page}</span><button class="button secondary" disabled={result.page*result.page_size>=result.total} onclick={()=>load(result.page+1)}>Next</button></div>{:else}<div class="empty">{scope==='all'?'No reports in the database match these filters.':`No reports match these filters for ${auth.office || 'your assigned office'}.`}</div>{/if}
<style>.scope-row{display:flex;align-items:center;justify-content:space-between;gap:1rem;background:white;border:1px solid var(--line);padding:.8rem 1rem;border-radius:9px;margin-bottom:1rem}.scope-row>div:first-child{display:grid;gap:.15rem}.scope-row span{color:var(--muted);font-size:.78rem}.scope-toggle{display:flex;border:1px solid var(--line);border-radius:8px;overflow:hidden}.scope-toggle button{border:0;background:white;color:var(--navy);padding:.6rem .85rem;font-weight:700;cursor:pointer}.scope-toggle button.active{background:var(--navy);color:white}.queue-guide{display:grid;grid-template-columns:auto auto 1fr auto auto 1fr;gap:.4rem .55rem;align-items:center;background:#edf4f5;border:1px solid #cddfe2;padding:.8rem 1rem;border-radius:9px;margin-bottom:1rem;font-size:.82rem}.queue-guide>span:not(.available-dot):not(.taken-dot){color:var(--muted)}.available-dot,.taken-dot{width:10px;height:10px;border-radius:50%;background:#20825e}.taken-dot{background:#78878d;margin-left:.8rem}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:.75rem;align-items:end;background:white;border:1px solid var(--line);padding:1rem;border-radius:10px;margin-bottom:1.2rem}.filters label{display:grid;gap:.35rem;font-size:.8rem;font-weight:700;color:var(--muted)}input,select{height:44px;border:1px solid #bac8ce;border-radius:7px;padding:.5rem;background:white}.list{display:grid;gap:.85rem}.notice{background:#e2f3eb;color:#176247;border:1px solid #b9dfcf;border-radius:7px;padding:.8rem;margin-bottom:1rem;font-weight:700}.error{margin-bottom:1rem}.pagination{display:flex;justify-content:center;align-items:center;gap:1rem;margin-top:1.4rem}@media(max-width:760px){.scope-row{align-items:flex-start;flex-direction:column}.scope-toggle{width:100%}.scope-toggle button{flex:1}.queue-guide{grid-template-columns:auto auto 1fr}.taken-dot{margin-left:0}.filters{grid-template-columns:1fr 1fr}.filters label:first-child{grid-column:1/-1}.filters .button{grid-column:1/-1}.filters select{width:100%}}</style>
